### ISSUE TITLE
splash screen..

### ISSUE THREAD

**Issue by soam1** [Elyahu41/Rabbi_Ovadiah_Yosef_Calendar_App#5]
@Elyahu41 Sir should I add a splash screen to the app (it helps people wait patiently while the app is loading user data)?

**Comment by NightScript370** [comment]
The app currently has a splash screen. It's either the app icon (Android 12+) or the English name of the app with a calendar icon (Android 11-)

What would be better would be to make a skeleton loading system. Loading screens aren't helpful to determine how things would be layed out while they are still loading

**Comment by NightScript370** [comment]
Upon further realization, the app uses a custom splash screen implementation prior to Android 12's standard API. The reason why we didn't switch over is because we want backwards compatibility with older devices and a better customization option (so that we could use our background that the app icon currently uses)

If you're able to figure out how to use a custom image as a splash screen background, that would also be an option.

**Comment by Elyahu41** [comment]
@soam1 What do you have in mind for the splash screen?

**Comment by Elyahu41** [comment]
Closing because no response
